name: Auto Merge Dependency Updates

on:
  - pull_request_target

permissions:
  contents: read
  pull-requests: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: tjenkinson/gh-action-auto-merge-dependency-updates@9628352bae4b424b3c3332f0368ca8ed3e7c048c
        with:
          repo-token: ${{ secrets.CI_GITHUB_TOKEN }}
          allowed-actors: renovate[bot]
